#			Programmation Repartie (4I400)
#		Makefile pour TM 6. Une messagerie instantanée en mémoire partagée


# Documentation: http://www.gnu.org/software/make/manual/make.html
CC =gcc
LFLAGS =-lpthread -lrt
#CFLAGS =-W -Wall -ansi -pedantic -Iinclude
CFLAGS =
BIN =bin/
OBJ =obj/
INCLUDE =include/
LIB =lib/
SRC =src/

.SUFFIXES:

HC=include/chat_common.h
O=


.PHONY: all clean test
all: $(BIN)chat_client $(BIN)chat_server
test: test-chat_client test-chat_server

test-chat_client: $(BIN)chat_client
	-bin/chat_client /client_shm:0 /serveur_sm:8

test-chat_server: $(BIN)chat_server
	-bin/chat_server /serveur_sm:8


clean: 
	rm -rf $(OBJ)*.o $(BIN)*

$(BIN)%: $(OBJ)%.o $O
	@if [ -d $(BIN) ]; then : ; else mkdir $(BIN); fi
	$(CC) -o $@ $^ $(LFLAGS)

$(OBJ)%.o: $(SRC)%.c $(HC)
	@if [ -d $(OBJ) ]; then : ; else mkdir $(OBJ); fi
	$(CC) $(CFLAGS) -o $@ -c $<

$(INCLUDE)%.h:
	@if [ -d $(INCLUDE) ]; then : ; else mkdir $(INCLUDE); fi

